### ISSUE TITLE
Release a new version with the `godeltaprof` fix

### ISSUE THREAD

**Issue by SweeXordious** [grafana/pyroscope-golang#38]
The latest release [v0.7.1](https://github.com/grafana/pyroscope-golang/releases/tag/v0.7.1) does not build using golang v1.21, as specified here: https://github.com/grafana/godeltaprof/issues/4. Please make a new release so that we can depend on it.

**Comment by korniltsev** [comment]
tagged v0.7.2

**Comment by korniltsev** [comment]
> Added and upgraded pyroscope to v0.7.2 and github.com/pyroscope-io/godeltaprof to v0.1.2 still unable to make build

What is the error?
What are the pyroscope-go and godeltaprof versions from your go.mod ?

**Comment by Srikarrao1** [comment]
go.mod
	github.com/pyroscope-io/client v0.7.2
	github.com/pyroscope-io/otel-profiling-go v0.5.0
        github.com/pyroscope-io/godeltaprof v0.1.2 // indirect

go.sum:
github.com/pyroscope-io/client v0.7.2 h1:OX2qdUQsS8RSkn/3C8isD7f/P0YiZQlRbAlecAaj/R8=
github.com/pyroscope-io/client v0.7.2/go.mod h1:FEocnjn+Ngzxy6EtU9ZxXWRvQ0+pffkrBxHLnPpxwi8=
github.com/pyroscope-io/godeltaprof v0.1.2 h1:MdlEmYELd5w+lvIzmZvXGNMVzW2Qc9jDMuJaPOR75g4=
github.com/pyroscope-io/godeltaprof v0.1.2/go.mod h1:psMITXp90+8pFenXkKIpNhrfmI9saQnPbba27VIaiQE=


getting error like

 
/home/user/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/home/user/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame

**Comment by korniltsev** [comment]
I recommend upgrading to github.com/grafana/pyroscope-go v1.1.1

**Comment by Srikarrao1** [comment]
I did 

--> Building Celestia
# github.com/pyroscope-io/otel-profiling-go
/home/user/go/pkg/mod/github.com/pyroscope-io/otel-profiling-go@v0.4.0/otelpyroscope.go:138:9: cannot use &p (value of type *tracerProvider) as trace.TracerProvider value in return statement: *tracerProvider does not implement trace.TracerProvider (missing method tracerProvider)
/home/user/go/pkg/mod/github.com/pyroscope-io/otel-profiling-go@v0.4.0/otelpyroscope.go:142:9: cannot use &profileTracer{…} (value of type *profileTracer) as trace.Tracer value in return statement: *profileTracer does not implement trace.Tracer (missing method tracer)
# github.com/pyroscope-io/godeltaprof/internal/pprof
/home/user/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/home/user/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
make: *** [Makefile:38: build] Error 1

**Comment by korniltsev** [comment]
did you try to update otel-profiling-go to v0.5.1 ?

**Comment by Srikarrao1** [comment]
Yes, it was already v0.5.1

require (
	github.com/grafana/otel-profiling-go v0.5.1
	github.com/grafana/pyroscope-go v1.1.1
)

**Comment by korniltsev** [comment]
The previous message says 0.4.0

> /home/user/go/pkg/mod/github.com/pyroscope-io/otel-profiling-go@v0.4.0

Were you able to build?
